// Generated by CoffeeScript 1.6.2
/*
Copyright (c) 2013 Markus Kohlhase <mail@markus-kohlhase.de>
*/


(function() {
  console.log("http://localhost:3000/")
  var app, express, fs, net, runCmd, vlcInstances;

  express = require('express');
  net = require('net');

  app = express();

  fs = require('fs');

  vlcInstances = require('../clients.js');

  app.use('/', express["static"](__dirname + './../public'));

  runCmd = function(cmd) {
    var i, _i, _len, _results;

    _results = [];
    for (_i = 0, _len = vlcInstances.length; _i < _len; _i++) {
      i = vlcInstances[_i];
      _results.push((function(i) {
        var client = new net.Socket();
        client.connect(i.port, i.host, function() {
          console.log('Connected to VLC RC interface at ' + i.host + ':' + i.port);
          client.write(cmd + '\n');
          client.destroy();
        });
        client.on('error', function(err) {
          console.error('Error connecting to VLC RC interface:', err);
        });
      })(i));
    }
    return _results;
  };

  app.get('/player/pause', function(req, res) {
    runCmd('pause');
    return res.end();
  });

  app.get('/player/stop', function(req, res) {
    runCmd('stop');
    return res.end();
  });

  app.get('/player/next', function(req, res) {
    runCmd('next');
    return res.end();
  });

  app.get('/player/prev', function(req, res) {
    runCmd('prev');
    return res.end();
  });

  app.get('/clients/*', function(req, res) {
    res.send(JSON.stringify(vlcInstances));
    return res.end();
  });

  app.listen(3000);

}).call(this);
